### ISSUE TITLE
Previous/Next content navigation on Supplier page

### ISSUE THREAD

**Issue by evanjfarmer** [realbig/teched-colormag-child-2#2]
The Previous/Next content navigation on the [Supplier](https://www.techedmagazine.com/supplier/) page does not behave as expected. 

Featured suppliers appear first, then the only option is to navigate to Previous suppliers and the user must continue clicking Previous to go backwards through alphabetical listings.

**Comment by d4mation** [comment]
Got a fix ready to go for this on Monday. Thanks for reporting this!
